#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/crossfade_patches.py from the
// Wyvern's riding lower chart (build 1.0.0.2976). Letting go of the stick
// crossfades into the hover instead of snapping to it.
namespace bm::broomchart
{
    inline constexpr HoverPatch kCrossfadePatches[] = {
        { 1, 0x0F08A, 0x00000000, 0x41700000 },   // m0004_ride_dragon_lower b13 -> 2B1E3C7C: crossfade 0 -> 15 frames
        { 1, 0x0F0F2, 0x00000000, 0x41700000 },   // m0004_ride_dragon_lower b15 -> E066175D: crossfade 0 -> 15 frames
    };
}
