#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/crossfade_patches.py from the
// Wyvern's riding lower chart (build 1.0.0.2976). Letting go of the stick
// crossfades into the hover instead of snapping to it, and the end of the
// takeoff into flight.
namespace bm::broomchart
{
    inline constexpr HoverPatch kCrossfadePatches[] = {
        { 1, 0x0F08A, 0x00000000, 0x41700000 },   // m0004_ride_dragon_lower b13 -> 2B1E3C7C: crossfade 0 -> 15 frames
        { 1, 0x0F0F2, 0x00000000, 0x41700000 },   // m0004_ride_dragon_lower b15 -> E066175D: crossfade 0 -> 15 frames
        // The takeoff ends nose up on the broom's 75u climb clip, and the flight
        // idle is level and aims at the camera. The Wyvern's takeoff ends in its
        // flight pose, so these cut (-1) or fade over 6 frames; the broom snapped.
        { 1, 0x1050E, 0xBF800000, 0x41700000 },   // m0004_ride_dragon_lower b114 takeoff -> E066175D (anim_end): -1 -> 15 frames
        { 1, 0x1091E, 0xBF800000, 0x41700000 },   // m0004_ride_dragon_lower b134 takeoff -> E066175D (input 10): -1 -> 15 frames
        { 1, 0x104A6, 0xBF800000, 0x41700000 },   // m0004_ride_dragon_lower b112 takeoff -> 0645598D (stick pushed): -1 -> 15 frames
        // By hand: the takeoff's own dip (B_Body_00 down 42 cm by frame 6, up
        // again by 13) and Kliff's push-off (3 frame fade, feet down at 6)
        // must start together; over the shipped 20 frame fade the dip came
        // about half a second late and shallow.
        { 1, 0x0F18E, 0x41A00000, 0x40800000 },   // m0004_ride_dragon_lower b18 -> takeoff 117F8F51: 20 -> 4 frames
        { 2, 0x0C604, 0x40C00000, 0x41700000 },   // m0004_ride_dragon_upper b27 F5150415 -> E066175D (airborne): 6 -> 15 frames
        // By hand: b27 also commands E066175D (target_hash2 at +0x18). Kliff's
        // lower layer moves only on such commands, and none reached it when
        // the takeoff went on into forward flight, so he stayed in the
        // push-off (upright) until the stick was let go. Now his E066175D
        // dispatcher takes b400 to the broom idle 588C2001 as flight begins.
        { 2, 0x0C614, 0x00000000, 0xE066175D },   // m0004_ride_dragon_upper b27: command E066175D for the rider
    };
}
