#pragma once

// Generated by speeder/pack_assets.py: the files the plugin hands the game
// for the speeder, each an RCDATA resource of the plugin (src/speeder.rc).
// A path no pack holds has a shipped file for the find and existence checks.
namespace bm::speederfiles
{
    struct File
    {
        const char* path;
        const char* standIn;
        int resource;
    };

    inline constexpr File kFiles[] = {
        { "character/model/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.pac", nullptr, 201 },
        { "character/modelproperty/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.pac_xml", nullptr, 202 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_run_f_ing_00.paa", nullptr, 203 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_runfast_f_ing_00.paa", nullptr, 204 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walk_f_ing_00.paa", nullptr, 205 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa", nullptr, 206 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa", nullptr, 207 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_ing_00.paa", nullptr, 208 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", nullptr, 209 },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_takeoff_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 210 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_run_f_ing_00_lod.paa", nullptr, 211 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_runfast_f_ing_00_lod.paa", nullptr, 212 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walk_f_ing_00_lod.paa", nullptr, 213 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_75d_ing_00_lod.paa", nullptr, 214 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_75u_ing_00_lod.paa", nullptr, 215 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_move_walkfast_f_ing_00_lod.paa", nullptr, 216 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", nullptr, 217 },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_takeoff_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 218 },
        { "character/texture/cd_r0032_00_speeder_0001.dds", "character/texture/cd_t0000_broom_0001.dds", 219 },
        { "character/texture/cd_r0032_00_speeder_0001_n.dds", "character/texture/cd_t0000_broom_0001_n.dds", 220 },
        { "character/texture/cd_r0032_00_speeder_0001_sp.dds", "character/texture/cd_t0000_broom_0001_sp.dds", 221 },
    };
}
