"""Put the speeder's files into the plugin.

    py -3 speeder/pack_assets.py <the broom's .pac_xml, unpacked>

Copies what build_mesh.py, build_rider.py and make_textures.py wrote under
speeder/out/files into mod/assets at the same game paths, adds the speeder's
material file (the broom's, naming the speeder's textures), and writes
mod/src/speeder.rc, which carries each file as an RCDATA resource, and
mod/src/game/speederfiles.h, which lists them with the shipped file the
find and existence checks see for a path no pack holds.
"""

import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.join(HERE, "..", "mod")
FILES = os.path.join(HERE, "out", "files")
ASSETS = os.path.join(MOD, "assets")
FIRST_ID = 201

BROOM_TEX = "character/texture/cd_t0000_broom_0001"
SPEEDER_TEX = "character/texture/cd_r0032_00_speeder_0001"
MATERIAL = "character/modelproperty/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.pac_xml"
RIDER = "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_"
RIDER_LOD = "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_"

# Paths no pack holds, and the shipped file standing in for each.
STAND_INS = {
    SPEEDER_TEX + ".dds": BROOM_TEX + ".dds",
    SPEEDER_TEX + "_n.dds": BROOM_TEX + "_n.dds",
    SPEEDER_TEX + "_sp.dds": BROOM_TEX + "_sp.dds",
    RIDER + "nor_std_takeoff_00.paa": RIDER + "nor_std_idle_01.paa",
    RIDER_LOD + "nor_std_takeoff_00_lod.paa": RIDER_LOD + "nor_std_idle_01_lod.paa",
}


def material(broom_xml):
    text = open(broom_xml, "rb").read().decode("utf-8")
    for tail in ("", "_n", "_sp"):
        old = f'_path="{BROOM_TEX}{tail}.dds"'
        assert text.count(old) == 1, old
        text = text.replace(old, f'_path="{SPEEDER_TEX}{tail}.dds"')
    # No height map: a parameter left out is the shader's default.
    start = text.index('<MaterialParameterTexture StringItemID="_heightTexture"')
    end = text.index("</MaterialParameterTexture>", start) + len("</MaterialParameterTexture>")
    line = text.rindex("\n", 0, start)
    text = text[:line] + text[end:]
    assert BROOM_TEX not in text
    return text.encode("utf-8")


def main():
    # mod/assets/sound is make_engine.py's.
    if os.path.isdir(os.path.join(ASSETS, "character")):
        shutil.rmtree(os.path.join(ASSETS, "character"))
    paths = []
    for root, _dirs, names in os.walk(FILES):
        for n in names:
            src = os.path.join(root, n)
            game = os.path.relpath(src, FILES).replace("\\", "/")
            dst = os.path.join(ASSETS, *game.split("/"))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copyfile(src, dst)
            paths.append(game)
    dst = os.path.join(ASSETS, *MATERIAL.split("/"))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "wb") as f:
        f.write(material(sys.argv[1]))
    paths.append(MATERIAL)
    paths.sort()
    missing = [p for p in STAND_INS if p not in paths]
    assert not missing, missing

    with open(os.path.join(MOD, "src", "speeder.rc"), "w", newline="\r\n") as f:
        f.write("// Generated by speeder/pack_assets.py: the speeder's files, one RCDATA\n")
        f.write("// resource each, listed in game/speederfiles.h.\n\n")
        for i, p in enumerate(paths):
            f.write(f'{FIRST_ID + i} RCDATA "../assets/{p}"\n')
        f.write("\n// The engine sounds from speeder/make_engine.py (game/speedersound.cpp).\n")
        for i, name in enumerate(("engine_idle", "engine_close", "engine_boost", "accelerate", "boost_start",
                                  "boost_stop", "startup", "shutdown")):
            f.write(f'{301 + i} RCDATA "../assets/sound/{name}.raw"\n')
    with open(os.path.join(MOD, "src", "game", "speederfiles.h"), "w", newline="\r\n") as f:
        f.write("#pragma once\n\n")
        f.write("// Generated by speeder/pack_assets.py: the files the plugin hands the game\n")
        f.write("// for the speeder, each an RCDATA resource of the plugin (src/speeder.rc).\n")
        f.write("// A path no pack holds has a shipped file for the find and existence checks.\n")
        f.write("namespace bm::speederfiles\n{\n")
        f.write("    struct File\n    {\n        const char* path;\n        const char* standIn;\n        int resource;\n    };\n\n")
        f.write("    inline constexpr File kFiles[] = {\n")
        for i, p in enumerate(paths):
            stand = f'"{STAND_INS[p]}"' if p in STAND_INS else "nullptr"
            f.write(f'        {{ "{p}", {stand}, {FIRST_ID + i} }},\n')
        f.write("    };\n}\n")
    total = sum(os.path.getsize(os.path.join(ASSETS, *p.split("/"))) for p in paths)
    print(f"{len(paths)} files, {total} bytes")
    for p in paths:
        print(" ", p)


main()
